name: ray
on: push
jobs:
  build:
    name: Build ray
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: maguowei/ray
          path: .
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true